name: Build and test mdcat

on:
  - push
  - pull_request

jobs:
  build-test:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04, macos-15]
        cc: [gcc, clang]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: make CC=${{ matrix.cc }}

  test:
    runs-on: ubuntu-24.04
    needs: build-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: make test

  sanitize:
    runs-on: ubuntu-24.04
    needs: build-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests with AddressSanitizer
        run: make test-sanitize

  format:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install clang-format
        run: sudo apt-get install -y clang-format

      - name: Check formatting
        run: make format && git diff --exit-code
