name: Build (macOS)

on:
  push:
  pull_request:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with make
        run: make

  test:
    runs-on: macos-latest
    needs: build-macos

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: make test
